### ISSUE TITLE
Chat client randomly places spaces in words when posting

### ISSUE THREAD

**Issue by CaribouKai** [HabitRPG/habitica-chat-extension#44]
Random spaces will sometimes appear in text after it posts to a chat. I was giving the benefit of the doubt that it may have just been me typoing, but it happened three times in a row with a copy/pasted link.

**Comment by Alys** [comment]
@CaribouKai Can you tell us which Guild(s) / Tavern / Party this happened in and the message you posted? If it's no longer visible due to the 200 message limit, tell us some word(s) from the messages if you remember them (we can then find the messages in the database).

Also if you're not [CaribouKai](https://habitica.com/profile/4c37bdea-9c8d-49ac-bacf-a977b46d9257) in Habitica let us know your Username there. I'm guessing you are though. :)

**Comment by CaribouKai** [comment]
It happens pretty much anywhere, though more often Tavern simply due to frequency of posting. Unfortunately I can't find any posts that contain one of the random spaces (it doesn't happen with every post), but the next time I notice one, I'll be sure to let you know when and where!

And yes, I'm CaribouKai there :)

**Comment by CaribouKai** [comment]
Alright, got a random space on my post in Tavern at 8:29PM EST!

(Also, many thanks for the return email. I didn't wanna muck up your inbox further with a thanks in reply to your thanks!)

**Comment by Alys** [comment]
@CaribouKai It was the message below, right? With the space appearing in "bar" where the `\n` is in the line below? That `\n` represents a line break so that might help track down why this is happening. Thank you!

"@Roshio It didn't seem to be any more than their normal favorite food when I fed them to mine. I could be wrong, though, I'm only going by what I saw the ba\nr do!"

Here's the relevant technical details about that post from the database, in case it's of use later:
```
{
	"text" : "@Roshio It didn't seem to be any more than their normal favorite food when I fed them to mine. I could be wrong, though, I'm only going by what I saw the ba\nr do!",
	"_id" : "dab16981-f2c7-4d5f-bad1-8817be4d6f71",
	"timestamp" : ISODate("2019-07-20T00:28:42.694Z"),
	"client" : "chat-extension",
	"uuid" : "4c37bdea-9c8d-49ac-bacf-a977b46d9257",
	"user" : "CaribouKai",
	"username" : "CaribouKai",
	"groupId" : "00000000-0000-4000-A000-000000000000",
}
```

**Comment by CaribouKai** [comment]
That's the one!

**Comment by cTheDragons** [comment]
The previous version of the chat client use to send the post to Habitica when you press Enter. It also added a carriage return. Hence why you can end up with spaces in the middle of a message if you move the cursor before the end and hit enter. 

I do not think this will be an issue in future versions as it has been change to Ctrl-Enter like the web client.

**Comment by cTheDragons** [comment]
Is it worth closing this issue as it appears to no longer be a problem?

**Comment by Alys** [comment]
I agree. We can reopen if it happens again. Thanks cTheDragons!
