### ISSUE TITLE
"Enter" does not send the message

### ISSUE THREAD

**Issue by JohnJSal** [HabitRPG/habitica-chat-extension#52]
According to the Wiki page, Enter sends the message and Shift+Enter inserts new lines, but both combinations are inserting new lines for me. The only way to send the message is to manually click the "Send" button. Should Enter be sending messages?

**Comment by benjaminbhollon** [comment]
Yeah, we made an update where Ctrl+Enter is the only keystroke that sends messages, just like on the website. The wiki probably needs to be updated.

**Comment by JohnJSal** [comment]
Thanks for the quick reply! I'll update the wiki as soon as I have a chance!

Take care!
John

**Comment by JohnJSal** [comment]
Hi again. Just wanted to mention that I tried Ctrl+Enter but it didn't
work. Nothing happened when I pressed them.

**Comment by benjaminbhollon** [comment]
Hmm... Maybe that part of the update hasn't been released yet? I'll check on it.

**Comment by benjaminbhollon** [comment]
Ah, commit 299fe7f hasn't been released yet because it conflicted with something else. I'll get to work on that within the next few days.

**Comment by JohnJSal** [comment]
Ok, thanks again for the quick replies! Take care!

**Comment by Alys** [comment]
I'm closing this because the Ctrl-Enter feature was implemented in https://github.com/HabitRPG/habitica-chat-extension/commit/299fe7f026834f9b449ca4fe1edf4d18aedda757

Note though that there's a new(?) bug which causes it and other features to fail, documented at https://github.com/HabitRPG/habitica-chat-extension/issues/55
