### ISSUE TITLE
Time is confusing

### ISSUE THREAD

**Issue by froggily** [HabitRPG/habitica-chat-extension#57]
When 12-hour time is selected, midnight displays as 0:00 am (a little weird but still understandable), and noon displays as 12:00 am (confusing because 12 am is midnight).

**Comment by junewerner** [comment]
Pull request #59 should resolve this.

**Comment by Alys** [comment]
@junewerner I'm very sorry, I should have posted on this issue earlier so that you would have seen it before you made the pull request.

The terms 12am and 12pm for midnight and noon are confusing no matter which way they are used, and opinions vary too much about which way is correct, especially when you consider usage in different countries. See [12-hour clock > Confusion at noon and midnight](https://en.wikipedia.org/wiki/12-hour_clock#Confusion_at_noon_and_midnight) for some examples; it shows that even within a single country the usage varies.

My suggestion is that we adopt the recommendation there to never use 12am and 12pm, and use "noon" and "midnight" instead.
That would have disadvantages for people who aren't fluent in English, but they could use a translation tool to learn the words and it's likely to be better overall for them since they'd have their own country's understanding of 12am/12pm which may differ from the usage implemented if we stick with am/pm.

**Comment by junewerner** [comment]
No worries! I agree that using noon is a good idea, but I'm worried about how to handle midnight. If a comment was made last night at midnight, should it read May 27th midnight, or May 26th midnight? Both could be confusing. We could just 'lie' and print out either 11:59 pm or 12:01 am if a timestamp is from midnight.

**Comment by Alys** [comment]
@junewerner Ah yes, good point. I think we should lie. :)  12:01am is probably the better option since the date portion of the date-time stamp wouldn't need to be changed. However I don't feel strongly about that so if you have a reason for using 11:59pm, I'm sure that would be okay too.

**Comment by junewerner** [comment]
Sounds good! We'll lie :) I'll get that changed and update the pull request when it's done.

**Comment by junewerner** [comment]
Just added a commit to the pull request, it should now display "12:01 am" at midnight and "noon" at noon.
