### ISSUE TITLE
Use the chat outside of Habitica.com

### ISSUE THREAD

**Issue by juanj** [HabitRPG/habitica-chat-extension#73]
I think this is a major feature and will require a lot of changes, but being able to use the chat outside Habitica may be a really useful.

I see 3 possible implementations for this
1. Inject the chat code on all websites. This may be the more straight forward, but it may be difficult to get the correct layout and can cause problems and interfere with the page layout.
2. Create an independent popup window for the chat.
3. Use a `browser_action` window like the one used to show the settings, to show the chat.

Will like to get some opinions on this.

**Comment by Alys** [comment]
> Inject the chat code on all websites.

I don't think we should do that. People would have privacy concerns about
whether that would allow the other websites to see your Habitica messages
and we'd need to spend time answering questions about that.

It's possible that the number of people wanting to use the extension on all
websites would be low, since it may interfere with the sites and be a
distraction.

**Comment by juanj** [comment]
I agree with you. That's the worse possible implementation.

I haven't thought of that. You may be right, having access to the chat all the time can be an extra reason to procrastinate, thus it may be against the philosophy of Habitica.

**Comment by cTheDragons** [comment]
Reviewing this issue should we then close this issue?
